#!/usr/bin/env bash
#
# Generate a standalone INDEX.md grouped by domain with bullet-point links.
# Unlike update-topic-index.sh (which edits README.md in-place),
# this produces a browsable, grouped view of all research topics.
#
# Usage:  bash scripts/generate-index.sh
# Run from the repository root.

set -euo pipefail

OUT="INDEX.md"
total=0

domain_label() {
  case "$1" in
    01-*) echo "Fundamentals" ;;
    02-*) echo "System Design" ;;
    03-*) echo "Languages" ;;
    04-*) echo "Frontend" ;;
    05-*) echo "Backend" ;;
    06-*) echo "DevOps & Infra" ;;
    07-*) echo "Databases" ;;
    08-*) echo "Security" ;;
    09-*) echo "Testing" ;;
    10-*) echo "Soft Skills" ;;
    11-*) echo "AI/ML" ;;
    *)    echo "Other" ;;
  esac
}

{
  echo "# Topic Index"
  echo ""
  echo "> Auto-generated by \`bash scripts/generate-index.sh\`"
  echo ""

  for dir in [0-9][0-9]-*/; do
    dir="${dir%/}"
    domain=$(domain_label "$dir")
    files=$(find "$dir" -name "*.md" ! -name "README.md" -type f | sort)

    [[ -z "$files" ]] && continue

    echo "### ${dir} — ${domain}"
    echo ""
    while IFS= read -r file; do
      title=$(head -1 "$file" | sed 's/^#[[:space:]]*//')
      echo "- [${title}](./${file})"
      total=$((total + 1))
    done <<< "$files"
    echo ""
  done

  pg_count=0
  for summary in playground/*/SUMMARY.md; do
    [[ -f "$summary" ]] || continue
    if [[ $pg_count -eq 0 ]]; then
      echo "### Playground Experiments"
      echo ""
    fi
    title=$(head -1 "$summary" | sed 's/^#[[:space:]]*//')
    echo "- [${title}](./${summary})"
    pg_count=$((pg_count + 1))
  done
  if [[ $pg_count -gt 0 ]]; then
    echo ""
  fi

  echo "---"
  echo ""
  echo "*${total} topics, ${pg_count} playground experiments*"
} > "$OUT"

echo "✓ Generated ${OUT}: ${total} topics, ${pg_count} playground experiments"
